{
	"version": 1633590388,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/ground.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/food-sheet0.png",
		"images/pointpar.png",
		"images/camera.png",
		"images/bgobj1.png",
		"images/bgobj2.png",
		"images/timer.png",
		"images/timer2.png",
		"images/darkpanel.png",
		"images/sprite-sheet0.png",
		"images/btn_restart-sheet0.png",
		"images/btn_play-sheet0.png",
		"images/particles.png",
		"images/btn_menu-sheet0.png",
		"images/btn_right-sheet0.png",
		"images/btn_left-sheet0.png",
		"images/btn_jump-sheet0.png",
		"images/playerstamina.png",
		"images/playerstaminabg.png",
		"images/power.png",
		"images/spike.png",
		"media/coin.m4a",
		"media/coin.ogg",
		"media/power.m4a",
		"media/power.ogg",
		"media/(robustmusic) john Åhlin - the coupon wizard 2.m4a",
		"media/(robustmusic) john Åhlin - the coupon wizard 2.ogg",
		"media/[royalty free music] 보통날 daily life (귀여운 편한 comfy).m4a",
		"media/[royalty free music] 보통날 daily life (귀여운 편한 comfy).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}